#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/TypeScriptWorkspace.yml'
      - 'docs/**'
      - 'ts/**'
      - 'README.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/TypeScriptWorkspace.yml'
      - 'docs/**'
      - 'ts/**'
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-main-build:
    name: Build UI extension for main branch
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      ci_tools_version: main
      duckdb_version: main
      exclude_archs: ${{ github.repository == 'duckdb/duckdb-ui' && 'wasm_mvp;wasm_eh;wasm_threads' || 'linux_arm64;linux_amd64_musl;osx_amd64;windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads' }}
      extension_name: ui

  duckdb-next-patch-build:
    name: Build UI extension for next patch (v1.5-variegata)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5-variegata
    with:
      ci_tools_version: v1.5-variegata
      duckdb_version: v1.5-variegata
      exclude_archs: ${{ github.repository == 'duckdb/duckdb-ui' && 'wasm_mvp;wasm_eh;wasm_threads' || 'linux_arm64;linux_amd64_musl;osx_amd64;windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads' }}
      extension_name: ui

  duckdb-stable-build:
    name: Build UI extension for DuckDB v1.5.5
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5-variegata
    with:
      ci_tools_version: v1.5-variegata
      duckdb_version: v1.5.5
      exclude_archs: ${{ github.repository == 'duckdb/duckdb-ui' && 'wasm_mvp;wasm_eh;wasm_threads' || 'linux_arm64;linux_amd64_musl;osx_amd64;windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads' }}
      extension_name: ui

  duckdb-stable-deploy:
    if: ${{ github.repository == 'duckdb/duckdb-ui' && ( startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' ) }}
    name: Deploy UI extension for DuckDB v1.5.5
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.5-variegata
    secrets: inherit
    with:
      extension_name: ui
      ci_tools_version: v1.5-variegata
      duckdb_version: v1.5.5
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}

  duckdb-lts-next-patch-build:
    name: Build UI extension binaries for next LTS patch (v1.4-andium)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4-andium
    with:
      ci_tools_version: v1.4-andium
      duckdb_version: v1.4-andium
      exclude_archs: ${{ github.repository == 'duckdb/duckdb-ui' && 'wasm_mvp;wasm_eh;wasm_threads' || 'linux_arm64;linux_amd64_musl;osx_amd64;windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads' }}
      extension_name: ui
      vcpkg_commit: '84bab45d415d22042bd0b9081aea57f362da3f35'

  duckdb-lts-build:
    name: Build UI extension for DuckDB v1.4.5 (LTS)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4-andium
    with:
      ci_tools_version: v1.4-andium
      duckdb_version: v1.4.5
      exclude_archs: ${{ github.repository == 'duckdb/duckdb-ui' && 'wasm_mvp;wasm_eh;wasm_threads' || 'linux_arm64;linux_amd64_musl;osx_amd64;windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads' }}
      extension_name: ui
      vcpkg_commit: '84bab45d415d22042bd0b9081aea57f362da3f35'

  duckdb-lts-deploy:
    if: ${{ github.repository == 'duckdb/duckdb-ui' && ( startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' ) }}
    name: Deploy UI extension for DuckDB v1.4.5 (LTS)
    needs: duckdb-lts-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.4-andium
    secrets: inherit
    with:
      extension_name: ui
      ci_tools_version: v1.4-andium
      duckdb_version: v1.4.5
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
